version: '3.8'

services: Computexfrontend
  frontend:
    image: frontend_image:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend: Computex
    image: backend_image:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://username:password@postgres:5432/dbname
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: computex
    ports:
      - "5432:5432"
